version: "3.8"

services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: ["node", "server.js"]
